### ISSUE TITLE
Option to export import synchronize

### ISSUE THREAD

**Issue by spardorp** [brian-girko/window-resizer#5]
Hi
I tried a few window-resizers and this one is great. Some difficulty sometimes with the percentages at which side, but okay.

I would love to see an option to export/import or synchronize settings. Either easily export the data file and option to import, or create a synchronize to google-drive.
This way you can easily get the same setup on all laptops with the same Google account, that would be awesome.

**Comment by brian-girko** [comment]
>  Some difficulty sometimes with the percentages at which side, but okay.

You just need to adjust the window, then open the popup. The extension automatically calculates the percents for you.

We are going to have import to JSON and export from JSON as of the next release.
